<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DomingoXpress - Rápido y Confiable</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Poppins', Arial, sans-serif;
            text-align: center;
            background-color: #f8f9fa;
            padding: 20px;
        }
        .container {
            max-width: 90%;
            width: 700px;
            margin: 20px auto;
            background: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        h1 {
            color: #ff6600;
            font-size: 32px;
            margin-bottom: 15px;
        }
        p {
            color: #333;
            font-size: 18px;
            margin-bottom: 20px;
        }
        .btn {
            display: inline-block;
            background: #25D366;
            color: white;
            padding: 18px 28px;
            text-decoration: none;
            border-radius: 8px;
            font-size: 20px;
            font-weight: bold;
            transition: background 0.3s;
            margin-bottom: 20px;
        }
        .btn:hover {
            background: #1da851;
        }
        .footer {
            margin-top: 30px;
            font-size: 14px;
            color: #666;
        }
        .map iframe {
            width: 100%;
            max-width: 350px;
            height: 250px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Bienvenido a DomingoXpress</h1>
        </div>
    </header>
    <main>
        <div class="container">
            <p>Tu servicio confiable de mandaditos y Uber en moto, disponible solo los domingos en el centro de Danlí.</p>
            <div class="horario">⏰ Horario: 6:00 AM - 7:00 PM</div>
            <a class="btn" href="https://wa.me/95657887" target="_blank" rel="noopener noreferrer">¡Haz tu pedido por WhatsApp!</a>
            <div class="moto-image">
                <h3>Nuestra Moto</h3>
                <img src="tu-imagen-de-moto.jpg" alt="Moto de DomingoXpress, lista para el servicio">
            </div>
            <div class="map">
                <h3>Ubicación</h3>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3873.437761441105!2d-86.58337462530214!3d14.033761192173814!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f66c6b8a4a2c3df%3A0xa2364b6e243e2e9a!2sDanl%C3%AD%2C%20El%20Para%C3%ADso%2C%20Honduras!5e0!3m2!1ses-419!2s!4v1700000000000" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </main>
    <footer>
        <div class="container footer">© 2025 DomingoXpress. Todos los derechos reservados.</div>
    </footer>
</body>
</html>
# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
